### PR TITLE
patch decorator at class level

### PR DESCRIPTION
**Pull request by poiati**
Hello Gary, 

I am a big fan of the simplicity of the Dingus framework. I also a client of destroyallsoftware.com (very nice content).

Take a look at that pull request, what it does is support for patch decorator at class level.

Thanks!

### CODE REVIEW

**Comment by garybernhardt** [comment]
Thanks, Paulo! I like the idea, but I think there's a problem right now. Some of the methods that it patches might not be tests. For example:

``` python
class TestUsers:
    def test_user_creation(self):
        ...
        user = self.create_user()
        ...

    def create_user(self):
        ...
```

This PR would patch the test_user_creation method, which is fine. But it would also patch create_user method, which isn't right, because create_user isn't a test method.

I see that you ignore methods starting with "_" to prevent this. I like that style, but we can't assume that people will name their helper methods in that way.

So how do we only patch methods that should be patched? One idea is to have the decorator define setup/teardown methods. But that doesn't work because the user might be defining those already. (Also, I find it very confusing when libraries define setup/teardown, which is one of the reasons I don't like DingusTestCase any more).

I can't think of any other way to only decorate the test methods. Any ideas?

**Comment by poiati** [comment]
Hi Gary! Yes, you have a point, we can't infer what methods should and
shouldn't be patched. The one who needs to know that is the developer
herself. What we can do is embrace the convention over configuration to
cover most part of the use cases and let the framework be configurable.

One of my ideas is add two key arguments to the @patch decorator with
default values. Ex:

``` python
def patch(object_path, new_object=NoArgument, only=r'^test', except=NoArgument)
 ...
```

The _only_ and _except_ arguments will be for the case of specific class
configuration. Ex:

``` python
@patch('my.module', only=r'^(test|should)')
class TestSystem(object):

   def test_system_version(self):
      ...
      self.my_helper...
      ...

   def should_show_a_welcome_when_startup(self):
      ...

   def my_helper(self):
      ...
```

If _only_ and _except_ are present in the decorator an exception should be
raised.

Another thing we need is a way to set a GLOBAL only and except, for example:

import dingus

``` python
dingus.class_patcher.only_methods = '^(should)'
```

And of course, update the documentation to make all that as clear a your
screencasts. What do you think Gary?

Cheers!

**Comment by garybernhardt** [comment]
That seems pretty complex... kinda the opposite of the simplicity that you mentioned in the original report.

I think the fundamental problem is that only the test runner knows which methods are tests. But we can't ask the test runner, because Dingus is test runner agnostic.

I'm not sure that there will be a good solution for this, since we can't know which methods to decorate. :(

**Comment by poiati** [comment]
Well, imo it still very simple for the majority of the cases and become
more complex when needed.

**Pull request closed without merging**
