### PR TITLE
The assert_call method

### PR DESCRIPTION
**Pull request by poiati**
Hello Gary,

What do you think about this?

``` python
from dingus import Dingus, assert_call

ding = Dingus('ding')

assert_call(ding, 'foo')
```

Guives:

``` text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/paulogpoiati2/virtualenv/dingus_test/lib/python2.7/site-packages/dingus.py", line 393, in assert_call
    raise AssertionError(message)
AssertionError: Expected a call to method: 'foo', args: (), kwargs: {}, dingus: <Dingus ding>
No calls recorded
```

---

Another example:

``` python
from dingus import Dingus, assert_call

ding = Dingus('ding')
ding.bar('hello', 'world', one=1, two=2)

assert_call(ding, 'foo')
```

Guives:

``` text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/paulogpoiati2/virtualenv/dingus_test/lib/python2.7/site-packages/dingus.py", line 393, in assert_call
    raise AssertionError(message)
AssertionError: Expected a call to method: 'foo', args: (), kwargs: {}, dingus: <Dingus ding>
Recorded calls: [('bar', ('hello', 'world'), {'two': 2, 'one': 1}, <Dingus ding.bar()>)]
```

Cheers,
Poiati.

### CODE REVIEW

**Comment by poiati** [comment]
Any thought?

Thanks.

**Comment by garybernhardt** [comment]
Can you explain the problem it solves?

**Comment by poiati** [comment]
The same problem the TestCase#assertEqual or nose.tools eq_ solves in contrast to a plain "assert expectation == 'foo'". I mean, a more descriptive output of what is going on.

**Comment by garybernhardt** [comment]
Seems reasonable to me. Do you think it should be a freestanding function? Or maybe a method on Dingus like this?

``` python
dingus.assert_call('frob', 1, 2, 3)
```

Or maybe this!

``` python
dingus.frob.assert_call(1, 2, 3)
```

to assert that `frob` was called with `1, 2, 3`? Mock has an assert_called_with method, I think. What do you think?

**Comment by poiati** [comment]
Looks good Gary, this more like a pure OOP style.

But in the case of:

``` python
dingus.frob.assert_call(1, 2, 3)
```

How we gonna achieve the equivalent to:

``` python
dingus.assert_call('()', 1, 2, 3)
```

**Comment by garybernhardt** [comment]
That would just be:

``` python
dingus.assert_call(1, 2, 3)
```

Even the "methods" in Dingus are just more dinguses:

``` python
>>> d = Dingus()
>>> d.f
<Dingus dingus_4299696912.f>
>>> d.f()
<Dingus dingus_4299696912.f()>
```

so you'd just say:

``` python
d.assert_call()
```

to assert that it was called with no args.

Does that make sense?

**Comment by poiati** [comment]
Yep, I know this, didn't know how I missed that lol, makes perfect sense.

**Comment by garybernhardt** [comment]
Awesome. Can you submit some commits that change your function to a method? I'd also rather have the (object) base class changes backed out if you don't mind. :)

**Comment by poiati** [comment]
Done Gary!

PS: I will update the base classes.

Thanks.

**Comment by garybernhardt** [comment]
There's still a top-level assert_call function in the diff. Could you remove that?

**Comment by poiati** [comment]
Of course.

**Comment by garybernhardt** [comment]
Merged. Thanks!

**Pull request merged**
