### PR TITLE
Fixes for Python 3, Python 2 compatibility not maintained.

### PR DESCRIPTION
**Pull request by Ciemaar**
This seems to be changes needed for Python 3, not sure if you had a strategy, but I needed support.

### CODE REVIEW

**Comment by garybernhardt** [comment]
Well, we can't just drop support for Python 2. Do you have a good sense of what the exact incompatibilities are? I see a lot of tests failing because of urllib, which they just use as an example, so it could be changed. Are the actual Dingus changes incompatible with Python 2 as well?

**Comment by Ciemaar** [comment]
Yeah, we can't just drop it, but it shows what we're up against as a first
cut.

The only change we should have in the main module would be the **div**
renaming. Combined 2/3 is possible, the biggest problem is that urllib2 is
referenced by text in the decorator. So switching to something consistently
named would be good there.

**Comment by garybernhardt** [comment]
That doesn't sound so bad. Do you have any interest in trying to get it to run on both versions? The examples and tests using urllib can be updated to use any function we know to exist in both versions. I think that datetime.now() would be a great one, since stubbing time out is a common real-world use-case.

**Comment by Ciemaar** [comment]
Yeah if you want 2/3 compatibility I can try it. How complete are the
tests? Can we trust them for this or do we need to add new ones?

**Comment by garybernhardt** [comment]
The tests should be very complete. It should even be true that every path is covered, although I haven't actually measured that. Go for it! :)

**Comment by garybernhardt** [comment]
closing for inactivity

**Pull request closed without merging**
